### ISSUE TITLE
AU Pay category updates missing

### ISSUE THREAD

**Issue by SergioBAM** [KeyPay/keypay-dotnet-v2#4]
Recent 2.0.3.26 release updates enums for My, Sg, and Uk. 
However, the Au enums for PayCategory were not updated.

Au / Enum / AuPayCategoryType.cs is missing Backpayment
as per: https://api.keypay.com.au/australia/reference/pay-category/au-pay-category--post?v=latest

**Comment by Blitheness** [comment]
Hi @SergioBAM, thanks for your report - we fixed this in v2.1.0.34 which is now available via NuGet.org
